
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # a
      - ./jenkins_home:/var/jenkins_home

      # Monta el socket de Docker
      - //var/run/docker.sock:/var/run/docker.sock

      # b
      - "C:/Users/juani/OneDrive/Documentos/ciencia de datos en produccion 2025-2/proyecto-final-CDP:/var/jenkins_home/workspace/proyecto-final-CDP"

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home: {} 